name: Auto Oraculo
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Verificar Go (para que pase la tarea)
        run: |
          go run main.go
      - name: Actualizar Oraculo
        run: |
          python update.py
      - name: Guardar index.html
        run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add index.html
          git diff --staged --quiet || git commit -m "V88.5 oraculo"
          git push
